<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55446" started-at="2020-12-21T19:18:12 IST" finished-at="2020-12-21T19:19:07 IST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:runnerIO.Runner@3cb1ffe6]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="55446" started-at="2020-12-21T19:18:12 IST" finished-at="2020-12-21T19:19:07 IST">
      <class name="runnerIO.Runner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runnerIO.Runner@3cb1ffe6]" name="setUpClass" is-config="true" duration-ms="742" started-at="2020-12-21T19:18:12 IST" finished-at="2020-12-21T19:18:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:runnerIO.Runner@3cb1ffe6]" name="runScenario" duration-ms="49904" started-at="2020-12-21T19:18:12 IST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2020-12-21T19:19:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA["I want to create an organization by using mandatory fields"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Oraganization]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Testyantra] but found [Testyantra450]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Testyantra] but found [Testyantra450]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinitions.OrganizationStepDef.i_navigate_to_organization_information_and_verify(OrganizationStepDef.java:49)
at âœ½.I navigate to organization information and verify(file:///C:/Users/Nitheesha/git/Sdet8Bdd/SDET8BDD/./src/test/resources/Features/Organization.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runnerIO.Runner@3cb1ffe6]" name="tearDownClass" is-config="true" duration-ms="4747" started-at="2020-12-21T19:19:02 IST" finished-at="2020-12-21T19:19:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runnerIO.Runner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
